export const SET_CURRENT_LESSON = 'SET_CURRENT_LESSON'
//获取轮播图
export const GET_SLIDERS = 'GET_SLIDERS'
export const GET_SLIDERS_SUCCESS = 'GET_SLIDERS_SUCCESS'
export const GET_LESSONS = 'GET_LESSONS'
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS'
//清除课程
export const CLEAR_LESSON = 'CLEAR_LESSON'

//设置用户信息
export const SET_USER_INFO = "SET_USER_INFO"
